void echo_exec(char * args);
void language_exec(char * args);
void test_exec(char * args);
void help_exec(char * args);
void idt_exec(char * args);
void prime_exec(char * args);
void malloc_exec(char * args);
void free_exec(char * args);
void memory_exec(char * args);
